In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/LoggiPredict.csv')

In [4]:
df.head(50)

    hour     drivers       rsme  ag    td
0    7.0  155.487213  34.235621  A1    D1
1    8.0  177.356384  31.271745  A1    D1
2    9.0  184.940872  29.472445  A1    D1
3   10.0  214.267624  37.792338  A1  D1\t
4   11.0  190.974426  26.308695  A1    D1
5   12.0  151.247589  37.422593  A1    D1
6   13.0  164.175949  27.410869  A1    D1
7   14.0  147.146759  32.194547  A1    D1
8   15.0  137.332870  30.536405  A1    D1
9   16.0  135.799789  25.971901  A1    D1
10  17.0  117.120819  36.088479  A1    D1
11  18.0  111.484627  32.609665  A1    D1
12  19.0  102.352463  29.581239  A1    D1
13  20.0   98.152916  22.951799  A1    D1
14  21.0   90.859131  20.152920  A1    D1
15   7.0  126.156937  28.203903  A2    D1
16   8.0  152.422211  36.810213  A2    D1
17   9.0  164.846863  37.587864  A2    D1
18  10.0  159.642105  36.618599  A2    D1
19  11.0  177.352264  27.573628  A2    D1
20  12.0  149.319427  38.967388  A2    D1
21  13.0  140.123291  42.211400  A2    D1
22  14.0  159.781631  25.660493  A2    D1
23  15.0  133.717010  32.995194  A2    D1
24  16.0  148.009567  22.716134  A2    D1
25  17.0  143.153427  24.140430  A2    D1
26  18.0  127.158554  24.058553  A2    D1
27  19.0  112.092163  23.997607  A2    D1
28  20.0   95.757690  24.265296  A2    D1
29  21.0   78.771805  27.480603  A2    D1
30   7.0  148.571640  30.640241  A1    D2
31   8.0  174.603394  30.970184  A1    D2
32   9.0  222.099030  44.607463  A1    D2
33  10.0  158.048859  37.740843  A1    D2
34  11.0  161.732788  35.971738  A1    D2
35  12.0  165.831116  27.991516  A1    D2
36  13.0  162.935944  27.834866  A1    D2
37  14.0  148.658646  31.247950  A1    D2
38  15.0  114.826973  48.395398  A1    D2
39  16.0  143.939468  23.121216  A1    D2
40  17.0  117.406113  35.801121  A1    D2
41  18.0  143.906403  24.596222  A1    D2
42  19.0  114.727554  22.809903  A1    D2
43  20.0   90.096962  28.096718  A1    D2
44  21.0   84.855469  23.347168  A1    D2

In [9]:
dff = df[(df['ag'] == 'A1') & (df['td'] == 'D1' )]
dff.head()

   hour     drivers       rsme  ag  td
0   7.0  155.487213  34.235621  A1  D1
1   8.0  177.356384  31.271745  A1  D1
2   9.0  184.940872  29.472445  A1  D1
4  11.0  190.974426  26.308695  A1  D1
5  12.0  151.247589  37.422593  A1  D1